apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-service-admission
  namespace: {{ .Values.common.name }}
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    name: https-webhook
    targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: {{ .Values.common.name }}
    app.kubernetes.io/name: {{ .Values.common.name }}