apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.name }}
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.common.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.common.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.deployment.prometheus.port }}"
        prometheus.io/scheme: "{{ .Values.deployment.prometheus.scheme }}"
    spec:
      serviceAccountName: {{ .Values.common.name }}
      containers:
      - image: "{{ .Values.deployment.image.name}}"
        imagePullPolicy: "{{ .Values.deployment.image.pullPolicy }}"
        name: {{ .Values.common.name }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: prometheus
          containerPort: {{ .Values.deployment.prometheusPort}}
        - name: readiness-port
          containerPort: {{ .Values.deployment.readyPort}}
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /ping
            port: 4001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        #  limits:
        #   cpu: "1"
        #   memory: "1Gi"
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/{{ .Values.common.name }}-configmap
          - -default-server-tls-secret=$(POD_NAMESPACE)/{{ .Values.common.name }}-server-secret
          # - -enable-cert-manager
          # - -enable-external-dns
          # - -v=3 # Enables extensive logging. Useful for troubleshooting.
          # - -report-ingress-status
          # - -external-service={{ .Values.common.name }}-service
          # - -enable-prometheus-metrics
