apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.name }}-server-secret
  namespace: {{ .Values.common.name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.common.cert }}
  tls.key: {{ .Values.common.key }}
