apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-configmap
  namespace: {{ .Values.common.name }}
  labels:
data:
  index.html: |
    <html>
    <h1>Welcome To Webapp 01</h1>
    </br>
    <h1>Hi! You are Trying to Access Webapp Through GKE Ingress </h1>
    </html